name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  run-all-tests:
    name: run-all-tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: unittest
      run: make test
